name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [task-service, ai-service, code-execution-service, web-browsing-service, filesystem-service]
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        cd backend/${{ matrix.service }}
        go mod tidy
        
    - name: Build
      run: |
        cd backend/${{ matrix.service }}
        go build -v ./...
        
    - name: Test
      run: |
        cd backend/${{ matrix.service }}
        go test -v ./...
        
  docker-build:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [task-service, ai-service, code-execution-service, web-browsing-service, filesystem-service]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./backend/${{ matrix.service }}
        push: true
        tags: yourusername/local-ai-agent-${{ matrix.service }}:latest
        
  deploy:
    needs: docker-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      run: |
        echo "Deploying backend services..."
        # Add deployment commands here
        # This could be SSH into a server and running docker-compose
        # or updating a Kubernetes deployment
