name: Auto Merge

on:
  pull_request:
    types: [labeled, unlabeled]
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
  status: {}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Auto merge
      uses: pascalgn/automerge-action@v0.15.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MERGE_LABELS: "automerge,!work in progress,!do not merge"
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "pull-request-title"
        MERGE_FORKS: "false"
        MERGE_RETRIES: "6"
        MERGE_RETRY_SLEEP: "10000"
        MERGE_REQUIRED_APPROVALS: "1"
