name: Generate Changelog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.0.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create changelog file
      run: |
        echo "# Changelog" > CHANGELOG.md
        echo "" >> CHANGELOG.md
        echo "${{ steps.changelog.outputs.changelog }}" >> CHANGELOG.md
        
    - name: Commit and push changelog
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add CHANGELOG.md
        git commit -m "docs: update changelog" || echo "No changes to commit"
        git push
