name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-go-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Update Go dependencies
      run: |
        for service in backend/*; do
          if [ -d "$service" ]; then
            echo "Updating dependencies for $service..."
            cd $service
            go get -u ./...
            go mod tidy
            cd -
          fi
        done
        
    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Go dependencies'
        title: 'chore: update Go dependencies'
        body: |
          This PR updates Go dependencies to their latest versions.
          
          This is an automated PR created by the Update Dependencies workflow.
        branch: update-go-dependencies
        base: main
        
  update-npm-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Update npm dependencies
      run: |
        for app in frontend/*; do
          if [ -d "$app" ]; then
            echo "Updating dependencies for $app..."
            cd $app
            npm update
            cd -
          fi
        done
        
    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update npm dependencies'
        title: 'chore: update npm dependencies'
        body: |
          This PR updates npm dependencies to their latest versions.
          
          This is an automated PR created by the Update Dependencies workflow.
        branch: update-npm-dependencies
        base: main
