name: Welcome

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          👋 Thanks for opening your first issue in the Local AI Agent System! We appreciate your contribution.
          
          Please make sure you've provided all the necessary information to help us understand and address your issue.
          
          Our team will review your issue as soon as possible.
        pr-message: |
          🎉 Thanks for opening your first pull request in the Local AI Agent System! We're excited to review your contribution.
          
          Please make sure your PR follows our contribution guidelines and includes appropriate tests and documentation.
          
          Our team will review your PR as soon as possible.
